language: ruby
cache: bundler
dist: trusty
rvm:
  - 2.3.0
  - 2.4.0
  - 2.5.0
gemfile:
  - gemfiles/rails_4.gemfile
  - gemfiles/rails_5.gemfile
script:
  - bundle exec rspec
  - bundle exec codeclimate-test-reporter
